version: 2
jobs:
  build:
    docker:
      - image: campenr/web-build:latest
    branches:
      only:
        - production
    steps:
      - add_ssh_keys:
          fingerprints:
            - "01:e3:85:7f:96:22:93:ac:b8:5e:06:ef:88:dc:84:e1"
      - run: ssh-keyscan vps1.campen.co >> ~/.ssh/known_hosts
      - checkout
      - run: git submodule sync && git submodule update --init
      - run:
          name: Build frontend
          command: |
            echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
            . $BASH_ENV
            . $NVM_DIR/nvm.sh --no-use
            nvm install
            nvm use
            npm config set "@fortawesome:registry" https://npm.fontawesome.com/ && \
            npm config set "//npm.fontawesome.com/:_authToken" $FONT_AWESOME_NPM_TOKEN
            npm install
            npm run build
      - deploy:
          name: deploy
          command: |
            rsync -v --archive --no-owner --no-group --delete --exclude="*.pyc" app link-shortener@vps1.campen.co:~/
            echo $PRODUCTION_VAULT_PASS > ./ansible/vault_passwords/production
            ansible-playbook ansible/playbook.yml -i ansible/hosts.ini -l production -t app-configure -v --vault-password-file=ansible/vault_passwords/production
